INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES('CATALOG-001', 'PRODUCT1', 100, 1500);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES('CATALOG-002', 'PRODUCT2', 110, 1000);
INSERT INTO CATALOG(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE) VALUES('CATALOG-003', 'PRODUCT3', 120, 2000);