### Health Check
GET localhost:8000/user-service/health_check
Content-Type: application/json

### user1
POST localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "yim3370@gmail.com",
  "password": "test1234",
  "name" : "임준희"
}

### user2
POST localhost:8000/user-service/users
Content-Type: application/json

{
"email": "yim3371@gmail.com",
"password": "test1234",
"name" : "임준희!"
}

### Get All User
GET localhost:8000/user-service/users

### Get User By Id
GET localhost:8000/user-service/users/f64aec53-7ec0-4ee2-bb38-0259cc004493

### login
POST localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "yim3370@gmail.com",
  "password": "test1234"

}



