### Health Check
GET localhost:8000/user-service/health_check
Content-Type: application/json
Authorization: token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5OTRiYTE2NC1lMmUyLTRiYjktOWNiYS1kYTkzMTkzZmU1MGYiLCJleHAiOjE2OTE4NTE2MDR9.IsjHaMNs6LaxjZnsoMEJqm0CQ3XGL2lvc8A7eu5KWkHa2bdWM0iU8fdPuyD6MhpylebwDjK4fLI7kmGqflETiA; Path=/; HttpOnly; SameSite=NONE
Authorization: userId=994ba164-e2e2-4bb9-9cba-da93193fe50f; Path=/; HttpOnly; SameSite=NONE

### user1
POST localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "yim3370@gmail.com",
  "password": "test1234",
  "name" : "임준희"
}

### user2
POST localhost:8000/user-service/users
Content-Type: application/json

{
"email": "yim3371@gmail.com",
"password": "test1234",
"name" : "임준희!"
}

### Get All User
GET localhost:8000/user-service/users

### Get User By Id
GET localhost:8000/user-service/users/f64aec53-7ec0-4ee2-bb38-0259cc004493

### login
POST localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "yim3370@gmail.com",
  "password": "test1234"
}



