spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/user-service
    username: sa
    password: '{cipher}AQBFXXVn/49LOOSqMv0Fi+Ox+YAdQvwyDScJKEAmbKKUtnAHOON1cLNXggnhJ8aizxtUgorYxZLc9HOvb9sNXK9GjA4sWO1K+iUzxI/vc7HKTIEYSDANgD4U2rb7/H8N98n15C9yp3WxMGiykmd5zuzyvBBn27OOssBJYuRtmcxPBLL/zY6sWvOXWpE6j3BEpGoiRyxLH4paQGXzNC5BD2Pm9W+4DcjpqzHQlZv692SX2AAoG+69yYMFEzUSwSrqRuoti2XGMqYX1gsxrNBhX6yjaDD9LImAOZ+7RBb6JxOfl37OK0uypJa2U2xyGoCA8VtcA6Gevl/0uoSZh1/n1Sg8g1olxz/06nn34ngE9ICwPL6QZPkQaFa4girRbFDX6so='