spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/user-service
    username: sa
    password: '{cipher}AQBFXXVn/49LOOSqMv0Fi+Ox+YAdQvwyDScJKEAmbKKUtnAHOON1cLNXggnhJ8aizxtUgorYxZLc9HOvb9sNXK9GjA4sWO1K+iUzxI/vc7HKTIEYSDANgD4U2rb7/H8N98n15C9yp3WxMGiykmd5zuzyvBBn27OOssBJYuRtmcxPBLL/zY6sWvOXWpE6j3BEpGoiRyxLH4paQGXzNC5BD2Pm9W+4DcjpqzHQlZv692SX2AAoG+69yYMFEzUSwSrqRuoti2XGMqYX1gsxrNBhX6yjaDD9LImAOZ+7RBb6JxOfl37OK0uypJa2U2xyGoCA8VtcA6Gevl/0uoSZh1/n1Sg8g1olxz/06nn34ngE9ICwPL6QZPkQaFa4girRbFDX6so='

token:
  expiration-time: 60000 #1분
  secret-key: '{cipher}AQATeC3lhSo3M4BB/vET8vlkpEJZzUK4MJvTJjoe/ZItzEE3PuzVtRpSGU0ylrQSO7wYuG/xpnMK/EwOUCDSHdyAJja0qqguy9UuZznmv/iGKtR8SO+dquV2hYn7jFXYeamBCAX7fDpwUv/eEmpTL/HJQ/BEVrHGgV5xYCRMNgRGBGalvL4+XE/TyQoL+U7yXOlCb4fernMl0GvYDXekjv65N3o2nFDqF3mop3uIZwMDsqFMiMhMrWgxuotTbw3KPVBYrLX12Swybd/GKFVxZVIPXGe6o0jNEfDD6gPr6Xo672ReOx0AgDaMY7SkOQ252BAZxUpgZ1bUhfOHSvepBS6QocXkFjPKUcYLjOABw/5CQiyLCbLiu6Wsa6SnUEy4GTQPPBWenUygPsoJMEoypVanq5Ty0WHADv/yk9ssgzTEcO6yg1nsKjgR2JTj9JUfqFFzxFkuHY/kyPdaDxxIJslI'

gateway:
  ip: 127.0.0.1